name: ntv
description: Open-source media player for your self-hosted content. Built on nSelf.
publish_to: 'none'
version: 1.0.9+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  dio: ^5.4.0
  video_player: ^2.8.0
  chewie: ^1.7.0
  go_router: ^13.0.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.0
  nself_auth_sdk:
    path: ../plugins-pro/paid/auth/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#030712"
  adaptive_icon_foreground: "assets/icons/app-icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true
  generate: true
